# zadaci petak 10.12.

In [2]:
import numpy as np

In [11]:
a = np.array([1, 2, 3])

python_polje = [[1,2,3,4], [5,6,7,8]]

In [30]:
a.dtype = np.float32
a.dtype

b = np.array(python_polje)
print(b.shape)
print(b.dtype)

(2, 4)
int64


In [35]:
c = np.zeros((4,2))
d = np.ones((2,3), dtype=np.uint8)

In [55]:
e = np.empty((2,3))

f = np.full((2,3), 7)
f

array([[7, 7, 7],
       [7, 7, 7]])

In [59]:
g = np.arange(10, 30, 5)
g

array([10, 15, 20, 25])

In [34]:
h = np.linspace(5, 10, num=5)
print(h)

[ 5.    6.25  7.5   8.75 10.  ]


In [36]:
i = np.array([1,2,3])
j = np.array([4,5,6])

print(i + j)
print(i - j)
print(i * j)
print(i / j)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [18]:
k = np.array([[1,2], [4,5]])
l = np.array([[7,8], [10,11]])

print(k * l)
m = np.matmul(k, l)

m


[[ 7 16]
 [40 55]]


array([[27, 30],
       [78, 87]])

In [19]:
n = np.array(
[[1,2,3,4],
[5,6,7,8],
[9,10,11,12],
[13,14,15,16]])



indexiranje - start, end, stop [start, end, step]

In [21]:
print(n[1::2,1::2])

[[ 6  8]
 [14 16]]


reshape iz 2-4 u 4-2

In [8]:
r = np.array([[1,2,3,4],[5,6,7,8]])

s = r.reshape(4,2)

s


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
t = r.swapaxes(0,1)
t

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [25]:
a = np.array([[1,2,3,4,5]])
b = a.swapaxes(0,1)
b

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [31]:
zbroj = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print(zbroj.sum())
print(zbroj.argmin())
print(zbroj.argmax())
print(zbroj.mean())
print(zbroj.cumsum())
print(zbroj.cumprod())
print(zbroj.std())
print(zbroj.var())
print(zbroj.ptp())
print(zbroj.mean())
print(zbroj.prod())
zbroj.sort()

zbroj

120
0
14
8.0
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120]
[            1             2             6            24           120
           720          5040         40320        362880       3628800
      39916800     479001600    6227020800   87178291200 1307674368000]
4.320493798938574
18.666666666666668
14
8.0
1307674368000


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# rješavanje zadataka

1. Zadatak
Stvorite Numpy array objekt iz Python 3D matrice veličine 3x4x2. Tip elemenata Numpy polja mora biti numpy.float64.
Ispišite na ekran:
● Broj osi
● Dimenzije polja
● Ukupni broj elemenata u polju
● Tip elemenata u polju
 
2. Zadatak
Promijenite tip Numpy polja iz prethodnog zadatka u np.int16, te ispišite na ekran novi tip polja.
3. Zadatak
Stvorite 2x7x3 Numpy polje tipa numpy.int32 čiji svi elementi imaju vrijednost 9.
4. Zadatak
Koristeći odgovarajuću Numpy funkciju, Stvorite Numpy polje koje sadrži svaki treći cjelobrojni broj u rasponu [3, 15>.
5. Zadatak
Koristeći odgovarajuću Numpy funkciju, Stvorite Numpy polje koji sadrži 12 jednoliko raspoređenih brojeva u rasponu [2, 19].
 
6. Zadatak
Stvorite jediničnu matricu dimenzije 4x4, te još jednu matricu istih dimenzija čiji svi elementi imaju vrijednost 9. Ispišite na ekran:
● Zbroj
● Razliku
● Umnožak (element po element)
● Količnik
 
7. Zadatak
Stvorite 1D ndarray od 10 elemenata proizvoljnih vrijednosti. Bez korištenja for petlje postavite svaki drugi element u rasponu indeksa [2, 7> na vrijednost 99.
8. Zadatak
Stvorite 2D ndarray dimenzija 5x6 s elementima proizvoljnih vrijednosti. Bez korištelja for petlje izdvojite svaki drugi stupac u zasebnu varijablu. Također, u zasebnu varijablu izdvojite posljednja 3 retka.
 
9. Zadatak
Stvorite 2D Numpy polje dimenzija 16x16 proizvoljnih vrijednosti. Stvorite novo Numpy polje koje sadrži iste elemente prvog polja, ali u obliku 4x8x8. Koja Numpy funkcija je prigodna kako bi se ovo ostvarilo? Vizualizirajte oblik novog ndarray-a. Dovoljna je skica na papiru ili skica u nekom digitalnom alatu.
 
10. Zadatak
Stvorite 3D Numpy polje dimenzija 3x576x720. Stvorite novo Numpy polje koje sadrži iste elemente prvog polja, ali u obliku 576x720x3. Koja Numpy funkcija je prigodna kako bi se ovo ostvarilo?
11. Zadatak
Stvorite 2D Numpy polje dimenzija 2x3. Ukoliko je srednja vrijednost svih elemenata veća od 10 ispišite sumu svih elemenata, u suprotnom ispišite vrijednost najvećeg elementa u polju.

## zadatak 1

In [52]:
rndm = np.random.randint(0,10, size=(3,4,2))
rndm

rndm_array = np.array(rndm)
rndm_array.dtype = np.float64
print(rndm_array.shape)
print(rndm_array.ndim)
print(rndm_array.size)
print(rndm_array.dtype)

(3, 4, 2)
3
24
float64


## zadatak 2

In [54]:
rndm_array.dtype = np.int16
print(rndm_array.dtype)

int16


## zadatak 3

Stvorite 2x7x3 Numpy polje tipa numpy.int32 čiji svi elementi imaju vrijednost 9.

In [58]:
only_nine = np.full((2, 7, 3), 9, dtype=np.int32)
only_nine

array([[[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]]], dtype=int32)

## zadatak 4

Koristeći odgovarajuću Numpy funkciju, Stvorite Numpy polje koje sadrži svaki treći cjelobrojni broj u rasponu [3, 15>.

In [60]:
my_array = np.arange(3, 15, 3)
my_array

array([ 3,  6,  9, 12])

## zadatak 5

Koristeći odgovarajuću Numpy funkciju, Stvorite Numpy polje koji sadrži 12 jednoliko raspoređenih brojeva u rasponu [2, 19].

In [62]:
my_arrray = np.linspace(2.0, 19.0, num=12)
my_arrray


array([ 2.        ,  3.54545455,  5.09090909,  6.63636364,  8.18181818,
        9.72727273, 11.27272727, 12.81818182, 14.36363636, 15.90909091,
       17.45454545, 19.        ])

## zadatak 6

Stvorite jediničnu matricu dimenzije 4x4, te još jednu matricu istih dimenzija čiji svi elementi imaju vrijednost 9. Ispišite na ekran:
● Zbroj
● Razliku
● Umnožak (element po element)
● Količnik

In [7]:
jedinicna = np.ones((4,4))
only_nineeee = np.full((4, 4), 9)

print(jedinicna + only_nineeee)
print(jedinicna - only_nineeee)
print(jedinicna / only_nineeee)
print(np.multiply(jedinicna, only_nineeee))


[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
[[-8. -8. -8. -8.]
 [-8. -8. -8. -8.]
 [-8. -8. -8. -8.]
 [-8. -8. -8. -8.]]
[[0.11111111 0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111 0.11111111]]
[[9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]]


## zadatak 7

Stvorite 1D ndarray od 10 elemenata proizvoljnih vrijednosti. Bez korištenja for petlje postavite svaki drugi element u rasponu indeksa [2, 7> na vrijednost 99.


In [14]:
rndm = np.random.rand(10)
rndm




array([0.58192257, 0.57890339, 0.53025259, 0.95654774, 0.34740071,
       0.19987479, 0.91921958, 0.58069761, 0.50118725, 0.87868046])

## zadatak 8

Stvorite 2D ndarray dimenzija 5x6 s elementima proizvoljnih vrijednosti. Bez korištelja for petlje izdvojite svaki drugi stupac u zasebnu varijablu. Također, u zasebnu varijablu izdvojite posljednja 3 retka.


## 9. Zadatak
Stvorite 2D Numpy polje dimenzija 16x16 proizvoljnih vrijednosti. Stvorite novo Numpy polje koje sadrži iste elemente prvog polja, ali u obliku 4x8x8. Koja Numpy funkcija je prigodna kako bi se ovo ostvarilo? Vizualizirajte oblik novog ndarray-a. Dovoljna je skica na papiru ili skica u nekom digitalnom alatu.


## 10. Zadatak
Stvorite 3D Numpy polje dimenzija 3x576x720. Stvorite novo Numpy polje koje sadrži iste elemente prvog polja, ali u obliku 576x720x3. Koja Numpy funkcija je prigodna kako bi se ovo ostvarilo?


## 11. Zadatak
Stvorite 2D Numpy polje dimenzija 2x3. Ukoliko je srednja vrijednost svih elemenata veća od 10 ispišite sumu svih elemenata, u suprotnom ispišite vrijednost najvećeg elementa u polju.